{% set name = "pyem" %}
{% set version = "0.68" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/asarnow/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 105c2fc9860dd927b051ceb90287cf5a4a2664ffa8ae0f95464263570ee733c5

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python
  entry_points:
    - cfsc.py = pyem.cli.cfsc:_main_
    - csparc2star.py = pyem.cli.csparc2star:_main_
    - ctf2star.py = pyem.cli.ctf2star:_main_
    - disparticle.py = pyem.cli.disparticle:_main_
    - emcalc.py = pyem.cli.emcalc:_main_
    - map.py = pyem.cli.map:_main_
    - mask.py = pyem.cli.map:_main_
    - mcstar.py = pyem.cli.mcstar:_main_
    - par2star.py = pyem.cli.par2star:_main_
    - project.py = pyem.cli.project:_main_
    - projection_subtraction.py = pyem.cli.projection_subtraction:_main_
    - stack.py = pyem.cli.stack:_main_
    - star.py = pyem.cli.star:_main_
    - star2bild.py = pyem.cli.star2bild:_main_
    - subparticles.py = pyem.cli.subparticles:_main_
    - varmap.py = pyem.cli.varmap:_main_

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numba >=0.41
    - numpy >=1.26
    - numexpr >=2.8.0
    - scipy >=1.2
    - matplotlib-base >=2.2
    - seaborn >=0.9
    - pandas >=0.23.4
    - pathos >=0.2.1
    - pyfftw >=0.12
    - healpy >=1.11
    - natsort >=6.0
    - starfile >=0.5.2

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyem
  commands:
    - cfsc.py --help
    - csparc2star.py --help
    - ctf2star.py --help
    - disparticle.py --help
    - emcalc.py --help
    - map.py --help
    - mask.py --help
    - mcstar.py --help
    - par2star.py --help
    - project.py --help
    - projection_subtraction.py --help
    - stack.py --help
    - star.py --help
    - star2bild.py --help
    - subparticles.py --help
    - varmap.py --help

about:
  home: https://github.com/asarnow/pyem
  summary: 'Python modules and command-line utilities for electron microscopy of biological samples.'
  description: |
    A collection of Python modules and command-line utilities for electron microscopy of biological samples.
    Cite as: Asarnow, D., Palovcak, E., Cheng, Y. UCSF pyem v0.5. Zenodo https://doi.org/10.5281/zenodo.3576630 (2019)
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asarnow
